export const podcastCategories = ['Tất cả', 'Âm nhạc', 'Đời sống', 'Công nghệ', 'Sáng tạo']

export const podcastShows = [
  {
    title: 'TMusic Backstage',
    host: 'TMusic Editorial',
    category: 'Âm nhạc',
    description: 'Những câu chuyện phía sau bản thu, sân khấu và các playlist đang lên.',
    cadence: 'Thứ sáu hàng tuần',
    episodeCount: 18,
    artwork: 'linear-gradient(135deg, #ff8d9a 0%, #ff6b57 42%, #281a39 100%)',
    initials: 'TB',
  },
  {
    title: 'Chuyện Nghe Đêm',
    host: 'Minh An',
    category: 'Đời sống',
    description: 'Một không gian kể chuyện nhẹ, chậm, hợp cho buổi tối và những chuyến đi dài.',
    cadence: '2 tập / tuần',
    episodeCount: 26,
    artwork: 'linear-gradient(135deg, #7bdff2 0%, #29d4ff 38%, #10243b 100%)',
    initials: 'CN',
  },
  {
    title: 'Studio Notes',
    host: 'Linh Phạm',
    category: 'Sáng tạo',
    description: 'Quy trình sáng tác, sản xuất âm thanh và cách một ý tưởng trở thành tập phát sóng.',
    cadence: 'Thứ ba hàng tuần',
    episodeCount: 12,
    artwork: 'linear-gradient(135deg, #ffe08a 0%, #ffb454 38%, #21324c 100%)',
    initials: 'SN',
  },
  {
    title: 'Tech Mix Daily',
    host: 'Tú Nguyễn',
    category: 'Công nghệ',
    description: 'Tin công nghệ ngắn gọn, dễ nghe, tập trung vào sản phẩm số và văn hóa internet.',
    cadence: 'Hàng ngày',
    episodeCount: 44,
    artwork: 'linear-gradient(135deg, #9eb5ff 0%, #6478ff 38%, #111827 100%)',
    initials: 'TM',
  },
]

export const podcastEpisodes = [
  {
    showTitle: 'TMusic Backstage',
    title: 'Một bản hit được chọn vào trang chủ như thế nào?',
    duration: '32 phút',
    publishedAt: '15/05/2026',
    category: 'Âm nhạc',
    status: 'Sẵn sàng import',
    previewAudioId: 'wikinews-0051-whitehouse',
  },
  {
    showTitle: 'Chuyện Nghe Đêm',
    title: 'Thành phố sau 23 giờ và những bài hát cũ',
    duration: '28 phút',
    publishedAt: '14/05/2026',
    category: 'Đời sống',
    status: 'Thiếu audio',
  },
  {
    showTitle: 'Studio Notes',
    title: 'Checklist thu âm tại nhà cho tập podcast đầu tiên',
    duration: '41 phút',
    publishedAt: '13/05/2026',
    category: 'Sáng tạo',
    status: 'Sẵn sàng import',
    previewAudioId: 'wikinews-020406-newsbrief',
  },
  {
    showTitle: 'Tech Mix Daily',
    title: 'AI trong sản xuất âm thanh: nhanh hơn hay rối hơn?',
    duration: '18 phút',
    publishedAt: '12/05/2026',
    category: 'Công nghệ',
    status: 'Cần cover',
    previewAudioId: 'wikinews-20060406-newsbrief',
  },
]

export const podcastImportFields = [
  { label: 'Show title', value: 'Tên chương trình' },
  { label: 'Host', value: 'Người dẫn / đơn vị sản xuất' },
  { label: 'Category', value: 'Chủ đề chính' },
  { label: 'Cover', value: 'Ảnh vuông 1:1' },
  { label: 'Episode audio', value: 'File audio hoặc URL' },
  { label: 'Publish date', value: 'Ngày phát hành' },
]

export const bulkPodcastDownloads = [
  {
    id: 'wikinews-0051-whitehouse',
    title: '0051 Whitehouse',
    showTitle: 'Wikinews Audio Brief',
    host: 'user:Amgine',
    category: 'News',
    duration: '00:25',
    durationSeconds: 26,
    sizeMb: 0.7,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:0051_Whitehouse.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/0051_Whitehouse.ogg',
  },
  {
    id: 'wikinews-0055-anthrax',
    title: '0055 Anthrax',
    showTitle: 'Wikinews Audio Brief',
    host: 'user:Amgine',
    category: 'News',
    duration: '00:29',
    durationSeconds: 29,
    sizeMb: 0.8,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:0055_Anthrax.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/16/0055_Anthrax.ogg',
  },
  {
    id: 'wikinews-0045-syrian-pullout',
    title: '0045 Syrian pullout',
    showTitle: 'Wikinews Audio Brief',
    host: 'user:Amgine',
    category: 'News',
    duration: '00:32',
    durationSeconds: 32,
    sizeMb: 0.87,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:0045_Syrian_pullout.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a8/0045_Syrian_pullout.ogg',
  },
  {
    id: 'wikinews-en-helicopter-crash',
    title: '14 US soldiers dead after helicopter crash in Iraq',
    showTitle: 'Spoken English Wikinews',
    host: 'Theory / Wikinews authors',
    category: 'News',
    duration: '00:51',
    durationSeconds: 52,
    sizeMb: 0.45,
    license: 'Public domain',
    sourcePage:
      'https://commons.wikimedia.org/wiki/File:En-14_US_Soliders_dead_after_helicopter_crash_in_Iraq.ogg',
    audioUrl:
      'https://upload.wikimedia.org/wikipedia/commons/e/e6/En-14_US_Soliders_dead_after_helicopter_crash_in_Iraq.ogg',
  },
  {
    id: 'wikinews-20050806-robin-cook',
    title: '20050806 Robin Cook dies',
    showTitle: 'Wikinews Audio Brief',
    host: 'Wikinews',
    category: 'News',
    duration: '00:58',
    durationSeconds: 59,
    sizeMb: 0.52,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:20050806_Robin_Cook_dies.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/20050806_Robin_Cook_dies.ogg',
  },
  {
    id: 'wikinews-020406-newsbrief',
    title: '020406 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'Ilyanep',
    category: 'News',
    duration: '01:19',
    durationSeconds: 80,
    sizeMb: 1.17,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:020406_newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/15/020406_newsbrief.ogg',
  },
  {
    id: 'wikinews-20050808-abc-anchor',
    title: '20050808 ABC News Anchor Pe',
    showTitle: 'Wikinews Audio Brief',
    host: 'Wikinews',
    category: 'News',
    duration: '01:25',
    durationSeconds: 85,
    sizeMb: 0.85,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:20050808_ABC_News_Anchor_Pe.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/20050808_ABC_News_Anchor_Pe.ogg',
  },
  {
    id: 'wikinews-020306-newsbrief',
    title: '020306 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'Ilyanep',
    category: 'News',
    duration: '01:34',
    durationSeconds: 94,
    sizeMb: 1.5,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:020306_newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/12/020306_newsbrief.ogg',
  },
  {
    id: 'wikinews-043006-newsbrief',
    title: '043006 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'User:Donato',
    category: 'News',
    duration: '08:33',
    durationSeconds: 513,
    sizeMb: 10.01,
    license: 'Public domain',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:043006_newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/af/043006_newsbrief.ogg',
  },
  {
    id: 'wikinews-turtlestack-intro',
    title: 'Turtlestack 15 Sec Intro',
    showTitle: 'Spoken English Wikinews',
    host: 'Turtlestack / Wikinews authors',
    category: 'News',
    duration: '00:12',
    durationSeconds: 12,
    sizeMb: 0.22,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Turtlestack_15_Sec_Intro.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Turtlestack_15_Sec_Intro.ogg',
  },
  {
    id: 'wikinews-turtlestack-outro',
    title: 'Turtlestack 60 Sec Outro',
    showTitle: 'Spoken English Wikinews',
    host: 'Turtlestack / Wikinews authors',
    category: 'News',
    duration: '00:54',
    durationSeconds: 55,
    sizeMb: 0.94,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:Turtlestack_60_Sec_Outro.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Turtlestack_60_Sec_Outro.ogg',
  },
  {
    id: 'wikinews-20060406-newsbrief',
    title: '20060406 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'Wikinews',
    category: 'News',
    duration: '01:30',
    durationSeconds: 90,
    sizeMb: 1.3,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:20060406-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/20060406-newsbrief.ogg',
  },
  {
    id: 'wikinews-033006-newsbrief',
    title: '033006 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'User:Phil-hong',
    category: 'News',
    duration: '01:35',
    durationSeconds: 95,
    sizeMb: 1.3,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:033006-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/033006-newsbrief.ogg',
  },
  {
    id: 'wikinews-032906-newsbrief',
    title: '032906 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'User:Phil-hong',
    category: 'News',
    duration: '01:39',
    durationSeconds: 100,
    sizeMb: 1.05,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:032906-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/97/032906-newsbrief.ogg',
  },
  {
    id: 'wikinews-20060401-newsbrief',
    title: '20060401 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'Wikinews',
    category: 'News',
    duration: '01:44',
    durationSeconds: 104,
    sizeMb: 1.26,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:20060401-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/20060401-newsbrief.ogg',
  },
  {
    id: 'wikinews-032506-newsbrief',
    title: '032506 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'user:Phil-hong',
    category: 'News',
    duration: '01:45',
    durationSeconds: 105,
    sizeMb: 1.59,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:032506-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/032506-newsbrief.ogg',
  },
  {
    id: 'wikinews-032606-newsbrief',
    title: '032606 newsbrief',
    showTitle: 'Wikinews Audio Brief',
    host: 'user:Phil-hong',
    category: 'News',
    duration: '01:48',
    durationSeconds: 109,
    sizeMb: 1.63,
    license: 'CC BY 2.5',
    sourcePage: 'https://commons.wikimedia.org/wiki/File:032606-newsbrief.ogg',
    audioUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/032606-newsbrief.ogg',
  },
  {
    id: 'wikinews-en-train-fuel-india',
    title: '15 killed attempting to steal fuel from train in India',
    showTitle: 'Spoken English Wikinews',
    host: 'kamnet / Wikinews authors',
    category: 'News',
    duration: '01:23',
    durationSeconds: 84,
    sizeMb: 0.93,
    license: 'CC BY 2.5',
    sourcePage:
      'https://commons.wikimedia.org/wiki/File:En-15_killed_30_injured_attempting_to_steal_fuel_from_train_in_India.ogg',
    audioUrl:
      'https://upload.wikimedia.org/wikipedia/commons/1/13/En-15_killed_30_injured_attempting_to_steal_fuel_from_train_in_India.ogg',
  },
]
