export const themeConfig = {
  name: 'spotifyRetonedAccent',
  description: 'Spotify-inspired dark music UI retuned with a soft blue-violet accent.',
  colors: {
    primaryAccent: 'oklch(78.5% 0.115 274.713)',
    primaryAccentHex: '#a3b3ff',
    primaryAccentHover: 'oklch(72% 0.115 274.713)',
    primaryAccentHoverHex: '#8f9eec',
    primaryAccentActive: 'oklch(66% 0.115 274.713)',
    primaryAccentActiveHex: '#7988d6',
    error: '#e61e32',
    warning: '#a00030',
    success: 'oklch(78.5% 0.115 274.713)',
    iconNeutral: '#b3b3b3',
    iconHover: '#ffffff',
    textPrimary: '#ffffff',
    textSecondary: '#b3b3b3',
    textTertiary: '#7c7c7c',
    textInverse: '#000000',
    surfaceMuted: '#9d968e',
    backgroundPrimary: '#121212',
    backgroundSecondary: '#1f1f1f',
    backgroundTertiary: '#282828',
    borderSubtle: '#404040',
    dividerSubtle: 'rgba(255, 255, 255, 0.1)',
    overlaySoft: 'rgba(255, 255, 255, 0.1)',
    overlayMedium: 'rgba(255, 255, 255, 0.2)',
    overlayStrong: 'rgba(255, 255, 255, 0.3)',
  },
  typography: {
    fonts: {
      sans:
        'SpotifyMixUI, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif',
      display:
        'SpotifyMixUITitle, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif',
      code:
        'SpotifyMixUI, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif',
    },
    roles: {
      display: { fontFamily: 'display', fontSize: '32px', fontWeight: 700, lineHeight: '40px' },
      heading1: { fontFamily: 'display', fontSize: '24px', fontWeight: 700, lineHeight: '32px' },
      heading2: { fontFamily: 'sans', fontSize: '16px', fontWeight: 700, lineHeight: '24px' },
      heading3: { fontFamily: 'sans', fontSize: '14px', fontWeight: 700, lineHeight: '21px' },
      body: { fontFamily: 'sans', fontSize: '16px', fontWeight: 400, lineHeight: '24px' },
      bodySmall: { fontFamily: 'sans', fontSize: '14px', fontWeight: 400, lineHeight: '21px' },
      button: { fontFamily: 'sans', fontSize: '16px', fontWeight: 700, lineHeight: '24px' },
      link: { fontFamily: 'sans', fontSize: '14px', fontWeight: 400, lineHeight: '21px' },
      caption: { fontFamily: 'sans', fontSize: '12px', fontWeight: 400, lineHeight: '18px' },
      code: { fontFamily: 'code', fontSize: '13px', fontWeight: 400, lineHeight: '20px' },
    },
  },
  spacing: {
    unit: 4,
    scale: {
      1: '4px',
      2: '8px',
      3: '12px',
      4: '16px',
      5: '20px',
      6: '24px',
      7: '28px',
      8: '32px',
      10: '40px',
      12: '48px',
      16: '64px',
      sidebarOffset: '160px',
    },
  },
  radii: {
    none: '0px',
    subtle: '4px',
    card: '6px',
    badge: '12px',
    filter: '50px',
    pill: '500px',
    full: '9999px',
    circle: '50%',
  },
  shadows: {
    none: 'none',
    subtle: '0 2px 4px rgba(0, 0, 0, 0.2)',
    raised: '0 4px 8px rgba(0, 0, 0, 0.3)',
    floating: '0 8px 16px rgba(0, 0, 0, 0.4)',
    high: '0 12px 24px rgba(0, 0, 0, 0.5)',
    artist: '0 4px 12px rgba(0, 0, 0, 0.3)',
  },
  layout: {
    sidebarWidth: '331px',
    desktopMainWidth: 'calc(100vw - 331px)',
    topNavHeight: '64px',
    minTouchTarget: '44px',
    preferredTouchTarget: '48px',
    sectionPaddingMobile: '24px',
    sectionPaddingTablet: '32px',
    sectionPaddingDesktop: '48px',
  },
  breakpoints: {
    mobileMax: '767px',
    tabletMin: '768px',
    tabletMax: '1024px',
    desktopMin: '1025px',
    largeDesktopMin: '1440px',
  },
  components: {
    button: {
      primary: {
        background: 'oklch(78.5% 0.115 274.713)',
        color: '#000000',
        fontSize: '16px',
        fontWeight: 700,
        padding: '12px 32px',
        borderRadius: '500px',
        border: 'none',
        height: '48px',
        hover: { background: 'oklch(72% 0.115 274.713)', color: '#000000' },
        active: { background: 'oklch(66% 0.115 274.713)', color: '#000000' },
        disabled: { background: '#404040', color: '#7c7c7c' },
      },
      secondary: {
        background: 'rgba(255, 255, 255, 0.1)',
        color: '#ffffff',
        fontSize: '16px',
        fontWeight: 700,
        padding: '12px 32px',
        borderRadius: '500px',
        border: '1px solid rgba(255, 255, 255, 0.2)',
        height: '48px',
        hover: {
          background: 'rgba(255, 255, 255, 0.2)',
          border: '1px solid rgba(255, 255, 255, 0.4)',
        },
        active: {
          background: 'rgba(255, 255, 255, 0.3)',
          border: '1px solid rgba(255, 255, 255, 0.6)',
        },
      },
      iconCircular: {
        background: '#1f1f1f',
        color: '#ffffff',
        width: '48px',
        height: '48px',
        padding: '12px',
        borderRadius: '50%',
        border: 'none',
        hover: { background: '#282828', color: '#ffffff' },
        active: { background: '#404040', color: 'oklch(78.5% 0.115 274.713)' },
      },
      iconOutlined: {
        background: 'transparent',
        color: '#b3b3b3',
        width: '48px',
        height: '48px',
        padding: '12px',
        borderRadius: '9999px',
        border: 'none',
        hover: { background: 'rgba(255, 255, 255, 0.1)', color: '#ffffff' },
        active: {
          background: 'oklch(78.5% 0.115 274.713 / 0.1)',
          color: 'oklch(78.5% 0.115 274.713)',
        },
      },
      smallText: {
        background: 'transparent',
        color: '#b3b3b3',
        fontSize: '14px',
        fontWeight: 700,
        padding: '4px 16px',
        borderRadius: '9999px',
        border: 'none',
        height: '32px',
        hover: { background: 'rgba(255, 255, 255, 0.1)', color: '#ffffff' },
      },
    },
    card: {
      content: {
        background: 'transparent',
        color: '#ffffff',
        padding: '12px',
        borderRadius: '6px',
        border: 'none',
        boxShadow: 'none',
        hover: { background: 'rgba(255, 255, 255, 0.1)' },
      },
      artist: {
        background: 'transparent',
        color: '#ffffff',
        padding: '0px',
        borderRadius: '50%',
        border: 'none',
        boxShadow: '0 4px 12px rgba(0, 0, 0, 0.3)',
        hoverOverlay: 'rgba(0, 0, 0, 0.3)',
      },
    },
    input: {
      searchDark: {
        background: '#1f1f1f',
        color: '#ffffff',
        fontSize: '16px',
        fontWeight: 400,
        padding: '12px 48px',
        borderRadius: '500px',
        border: 'none',
        height: '48px',
        placeholderColor: '#b3b3b3',
        focus: {
          background: '#282828',
          boxShadow: '0 0 0 2px oklch(78.5% 0.115 274.713)',
        },
      },
      filterLightSmall: {
        background: '#ffffff',
        color: '#000000',
        fontSize: '12.8px',
        fontWeight: 400,
        padding: '6px 35px 6px 15px',
        borderRadius: '50px',
        border: '1px solid #707070',
        height: '31px',
        width: '100%',
        focus: { border: '1px solid #000000' },
      },
    },
    navigation: {
      sidebar: {
        background: 'transparent',
        color: '#b3b3b3',
        width: '331px',
        activeItem: {
          color: '#ffffff',
          leftBorder: '4px solid oklch(78.5% 0.115 274.713)',
        },
        hoverItem: {
          color: '#ffffff',
          background: 'rgba(255, 255, 255, 0.1)',
        },
      },
      topBar: {
        background: '#121212',
        color: '#ffffff',
        padding: '16px 32px',
        height: '64px',
        borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
        position: 'fixed',
        top: 0,
        zIndex: 100,
      },
    },
    badge: {
      success: {
        background: 'oklch(78.5% 0.115 274.713 / 0.15)',
        color: 'oklch(78.5% 0.115 274.713)',
        fontSize: '12px',
        fontWeight: 700,
        padding: '4px 12px',
        borderRadius: '12px',
        border: '1px solid oklch(78.5% 0.115 274.713)',
      },
      error: {
        background: 'rgba(230, 30, 50, 0.15)',
        color: '#e61e32',
        fontSize: '12px',
        fontWeight: 700,
        padding: '4px 12px',
        borderRadius: '12px',
        border: '1px solid #e61e32',
      },
    },
  },
}

export const themeCssVariables = {
  '--bg-app': themeConfig.colors.backgroundPrimary,
  '--bg-elevated': themeConfig.colors.backgroundSecondary,
  '--bg-surface': themeConfig.colors.backgroundSecondary,
  '--bg-surface-2': themeConfig.colors.backgroundTertiary,
  '--bg-soft': themeConfig.colors.backgroundTertiary,
  '--border-soft': themeConfig.colors.dividerSubtle,
  '--border-strong': 'oklch(78.5% 0.115 274.713 / 0.4)',
  '--primary': themeConfig.colors.primaryAccent,
  '--primary-hex': themeConfig.colors.primaryAccentHex,
  '--primary-hover': themeConfig.colors.primaryAccentHover,
  '--primary-hover-hex': themeConfig.colors.primaryAccentHoverHex,
  '--primary-active': themeConfig.colors.primaryAccentActive,
  '--secondary': themeConfig.colors.iconNeutral,
  '--tertiary': themeConfig.colors.primaryAccent,
  '--neutral': themeConfig.colors.textTertiary,
  '--danger': themeConfig.colors.error,
  '--warning': themeConfig.colors.warning,
  '--success': themeConfig.colors.success,
  '--text-primary': themeConfig.colors.textPrimary,
  '--text-secondary': themeConfig.colors.textSecondary,
  '--text-dim': themeConfig.colors.textTertiary,
  '--text-base': themeConfig.colors.textPrimary,
  '--text-inverse': themeConfig.colors.textInverse,
  '--surface-muted': themeConfig.colors.surfaceMuted,
  '--surface-hover': themeConfig.colors.overlaySoft,
  '--divider-subtle': themeConfig.colors.dividerSubtle,
  '--scrollbar-size': '10px',
  '--scrollbar-track': 'transparent',
  '--scrollbar-thumb': themeConfig.colors.borderSubtle,
  '--scrollbar-thumb-hover': themeConfig.colors.primaryAccentHover,
  '--scrollbar-thumb-active': themeConfig.colors.primaryAccentActive,
  '--button-radius': themeConfig.radii.pill,
  '--card-radius': themeConfig.radii.card,
  '--badge-radius': themeConfig.radii.badge,
  '--sidebar-width': themeConfig.layout.sidebarWidth,
}

export function applyThemeConfig(target) {
  const root = target ?? (typeof document === 'undefined' ? null : document.documentElement)

  if (!root) {
    return
  }

  Object.entries(themeCssVariables).forEach(([name, value]) => {
    root.style.setProperty(name, value)
  })

  root.dataset.theme = themeConfig.name
}

export default themeConfig
