export const appPaths = {
  home: '/',
  podcast: '/podcast',
  section: '/section/:sectionKey',
  search: '/search',
  support: '/support',
  supportArticle: '/support/:slug',
  footer: {
    about: '/about',
    jobs: '/jobs',
    news: '/news',
    forArtists: '/for-artists',
    developers: '/developers',
    advertising: '/advertising',
    investors: '/investors',
    vendors: '/vendors',
    mobileApp: '/mobile-app',
    countries: '/countries',
    importMusic: '/import-music',
    legal: '/legal',
    safetyPrivacy: '/safety-privacy',
    privacy: '/privacy',
    cookies: '/cookies',
    adsInfo: '/ads-info',
    accessibility: '/accessibility',
  },
  plans: {
    individual: '/plans/individual',
    student: '/plans/student',
    free: '/plans/free',
  },
  auth: {
    login: '/login',
    register: '/register',
    callback: '/auth/callback',
  },
  admin: {
    root: '/admin',
    login: '/admin/login',
    songs: '/admin/songs',
    artists: '/admin/artists',
    podcasts: '/admin/podcasts',
    importSongs: '/admin/import',
    importPodcasts: '/admin/podcasts/import',
    users: '/admin/users',
    admins: '/admin/admins',
    artistAccounts: '/admin/artist-accounts',
    artistApplications: '/admin/artist-applications',
  },
  artist: {
    portal: '/artist',
    login: '/artist/login',
    register: '/artist/register',
    dashboard: '/artist/dashboard',
  },
}
