export const appPaths = {
  home: '/',
  support: '/support',
  supportArticle: '/support/:slug',
  footer: {
    about: '/about',
    jobs: '/jobs',
    news: '/news',
    forArtists: '/for-artists',
    developers: '/developers',
    advertising: '/advertising',
    investors: '/investors',
    vendors: '/vendors',
    mobileApp: '/mobile-app',
    countries: '/countries',
    importMusic: '/import-music',
    legal: '/legal',
    safetyPrivacy: '/safety-privacy',
    privacy: '/privacy',
    cookies: '/cookies',
    adsInfo: '/ads-info',
    accessibility: '/accessibility',
  },
  plans: {
    individual: '/plans/individual',
    student: '/plans/student',
    free: '/plans/free',
  },
  auth: {
    login: '/login',
    register: '/register',
    callback: '/auth/callback',
  },
  admin: {
    root: '/admin',
    login: '/admin/login',
    importSongs: '/admin/import',
  },
  artist: {
    portal: '/artist',
    login: '/artist/login',
    register: '/artist/register',
    dashboard: '/artist/dashboard',
  },
}
